### PR TITLE
Homeykit fixes

### PR DESCRIPTION
**Pull request by robertklep**
Some capability changes so the driver works better with apps that perform capability sniffing, like HomeyKit.

### CODE REVIEW

**Comment by robertklep** [comment]
@RobinBol not sure what the Codacy issue is, let me know if I need to change anything.

**Comment by robertklep** [comment]
@RobinBol force-pushed an update that doesn't increase the versions in `app.json` and `package.json`. Codacy now doesn't show up at all...?

**Comment by RobinBol** [comment]
Hi! Thanks for your PR, I was just wondering why these changes are necessary? I guess HomeKit expects a thermostat device to have some sort of thermostat mode (which makes sense)? But can't HomeyKit handle capabilities with a dot or what is the issue?

**Comment by robertklep** [comment]
@RobinBol HomeyKit uses `device.state.measure_temperature` to retrieve the measured temperature of a thermostat, which makes sense to me because it's a system capability defined for the thermostat class.

Even if it would have some sort of generic support for capabilities with a period in them, that still would require some sort of consensus between all thermostat-app-developers to use the same capability names across all apps, otherwise it wouldn't know how to map the Homey capability to the correct HomeKit characteristic.

**Comment by RobinBol** [comment]
I see, thanks for the clarification!

**Comment by RobinBol** [comment]
FYI, published as beta (2.0.1) in the app store.

**Comment by robertklep** [comment]
Thanks!

**Pull request merged**
